apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: second-snapshot-demo
spec:
  volumeSnapshotClassName: csi-driver-lvm-s3
  source:
    persistentVolumeClaimName: csi-pvc
