
lvm:
  # This one you should change
  devicePattern: /dev/nvme[0-9]n[0-9]

  # timeout for lvm provisioner operations (lvcreate/lvremove) in seconds"
  lvmTimeout: 60

  # these are primariliy for testing purposes
  vgName: csi-lvm
  driverName: lvm.csi.metal-stack.io
  storageClassStub: csi-driver-lvm

rbac:
  create: true
  pspEnabled: true

snapshots:
  enabled: false

  # name of the secret to use (will be created by the helm chart)
  secret: csi-driver-lvm-s3-snapshot-params

  ## your s3 credentials (will be content of the secret)
  # s3Endpoint: https://s3gateway.example.com
  # s3AccessKey: MYS3ACCESSKEY
  # s3SecretKey: MYS3SECRETKEY
  # s3BucketName: my-bucket

  ## passphrase with wich the backups will be encrypted
  # encryptionPassphrase: myS3cr3tEncryptionPassphrase

  # timeout for snapshot provisioner operations (snapshot create/restore) in seconds
  # increase, if you have very large volumes (or a low bandwith connection to the s3 endpoint)
  snapshotTimeout: 3600

  # amount (in percent) for lvm snapshots during snapshot creation
  # increase if you have volumes with high amount of write operations during snapshot creation
  lvmSnapshotBufferPercentage: 10

## enable, if you want to install storage classes with v0.3.x backward-compatible `csi-lvm-sc-*` names
compat03x: false

pluginImage:
  repository: metalstack/lvmplugin
  tag: v0.4.0
  pullPolicy: IfNotPresent

provisionerImage:
  repository: metalstack/csi-lvmplugin-provisioner
  tag: v0.4.0
  pullPolicy: IfNotPresent

externalImages:
  csiAttacher: quay.io/k8scsi/csi-attacher:v2.2.0
  csiResizer: quay.io/k8scsi/csi-resizer:v0.5.0
  csiNodeDriverRegistrar: quay.io/k8scsi/csi-node-driver-registrar:v1.3.0
  csiProvisioner: quay.io/k8scsi/csi-provisioner:v1.6.0
  csiLivenessprobe: quay.io/k8scsi/livenessprobe:v1.1.0
  csiSnapshotController: k8s.gcr.io/sig-storage/snapshot-controller:v3.0.2
  csiSnapshotter: quay.io/k8scsi/csi-snapshotter:v3.0.2
